# # OIP v0.2.0 Baseline Verification
## Reproducible Software Audit Using Controlled Synthetic Scenarios

**Project:** Organic Intelligence Protocol (OIP)  
**Verification Target:** Original OIP v0.2.0 Decision Engine  
**Verification Type:** Research-Stage Software Verification  
**Methodology:** Evidence-First, Fail-Closed, Reproducible Testing  
**Current Status:** PLANNED — NOT YET EXECUTED

---

## 1. Research Objective

This notebook evaluates whether the original OIP v0.2.0 decision engine behaves according to its specified decision rules under controlled synthetic inputs.

The objective is to make the verification independently repeatable. Another researcher should be able to inspect the test definitions, reproduce the execution, compare expected and observed results, and verify the integrity of the exported artifacts.

This notebook evaluates software behavior. It does not, by itself, validate the scientific theory or every version of the OIP protocol.

## 2. Verification Scope

The verification covers:

- Core decision behavior
- Edge cases and invalid inputs
- Output structure and field requirements
- Configuration and field immutability
- Decision precedence
- A defined exhaustive categorical test matrix
- Reproducible result exports and integrity checks

The original decision engine must remain unchanged during baseline testing.

Any proposed improvements or modified implementations must be evaluated separately against the frozen baseline.

## 3. Source Identity and Integrity

**Reference source file:** `verified_oip_v0_2_0_source.py`

**Expected SHA-256:**

`1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5`

Before executing tests, the verification must establish that the source bytes match the expected digest.

The hash must be calculated from the actual canonical source bytes, not copied from this document or assigned manually.

If the source is missing, altered, or fails the hash check, execution must stop until the discrepancy is resolved.

A matching hash establishes source identity. It does not establish software correctness.

The original implementation's configuration types and behavior must not be silently changed during verification.

## 4. Controlled Synthetic Scenarios

Synthetic inputs will represent fictional situations such as:

- **Medical review:** A required report is missing or a review remains incomplete.
- **Financial verification:** Supporting documents contain conflicting information.
- **Infrastructure safety:** A required inspection or review has failed.

These scenarios provide understandable labels for software tests. They are not real patient assessments, actual credit decisions, or engineering safety evaluations.

Expected outcomes must be defined from the applicable, documented decision rules before the corresponding tests run. They must not be invented from the scenario description or generated by simply copying the engine's own output.

## 5. Predeclared Test Inventory

The planned verification contains 114 test records:

| Test category | Planned records |
|---|---:|
| Core decision tests | 14 |
| Edge-case tests | 8 |
| Input-validation tests | 5 |
| Output-contract tests | 5 |
| Field-immutability tests | 3 |
| Configuration-stability tests | 4 |
| Decision-precedence tests | 3 |
| Exhaustive categorical matrix | 72 |
| **Total planned** | **114** |

The 72-case matrix represents:

3 evidence statuses × 3 review results × 2 conflict values × 4 prior states = 72 combinations.

This is exhaustive only over those declared categories. It does not cover every possible Python input, execution environment, or real-world situation.

The planned count is not evidence that the tests have already been implemented or executed. The final report must state the actual number executed.

## 6. Evidence Ledger and Result Rules

Every executed test must preserve, at minimum:

- Unique test ID
- Scenario label and description
- Input conditions
- Expected outcome and its rule reference
- Actual outcome returned by the original engine
- PASS, FAIL, or UNRESOLVED status
- Error details, where applicable

PASS is permitted only when the observed result matches the independently specified expected result.

A failed test must remain recorded as failed. An unresolved test must not be converted to a pass.

A source-integrity failure must stop execution. An individual test failure should be recorded accurately; other independent tests may continue so that the failure pattern can be inspected. A failed test prevents an unqualified successful-verification claim.

## 7. Reproducibility Requirements

The completed notebook must:

1. Identify the exact source implementation.
2. Record the software and runtime environment.
3. Use explicit, reproducible test inputs.
4. Keep expected results separate from observed results.
5. Avoid silent imputation, fabricated results, and hidden manual overrides.
6. Execute from a clean runtime in a documented order.
7. Preserve the actual results and disclose failed or unresolved checks.
8. Produce artifacts that another researcher can independently inspect.

Any dependency, environmental assumption, or deviation from the original implementation must be documented.

## 8. Export and Integrity Verification

After execution, the notebook will export the actual test records to JSON and CSV.

The export process must verify that:

- The exported records match the executed test records.
- Test IDs and expected and observed outcomes are preserved.
- Record counts agree across the result files and summary.
- SHA-256 digests are calculated from the actual exported bytes.
- The generated files can be read back and checked.

A hash demonstrates file integrity relative to that digest. It does not independently prove that the underlying test results are correct.

## 9. Independent Researcher Retest

A researcher should be able to obtain the project files, follow the documented setup instructions, run the notebook from a clean runtime, and compare their outputs with the published audit artifacts.

The repository should eventually include:

- The original, identifiable source implementation
- The verification notebook
- Test definitions and expected-result references
- Environment and execution instructions
- Machine-readable results in JSON and CSV
- A result summary and SHA-256 manifest
- A limitations and claim-boundaries statement

Only artifacts that have actually been generated and verified may be published as completed results.

## 10. Claim Boundaries

A successful verification may support the limited claim that the tested OIP v0.2.0 implementation produced the expected outcomes for the declared synthetic inputs.

It does not, by itself, establish:

- Scientific or causal validity
- Real-world safety or decision-making effectiveness
- Production readiness
- Compliance with OIP v1.0.26, v1.0.30, or any other protocol version
- Correctness for inputs or conditions not tested

Protocol compliance requires a separate, traceable comparison between the authoritative protocol requirements and the implementation.

## 11. Release and Reporting Policy

The release status is currently **NOT APPROVED**.

A final verification report may be issued only after the source identity check, test execution, result reconciliation, export integrity checks, and evidence review are completed.

All conclusions must remain proportional to the evidence actually produced.

**Core principle: Evidence before claims. Preserve failures. Do not report unexecuted tests as completed.**

In [1]:
# Cell 2 — Verify and load the exact v0.2.0 baseline source

import hashlib

EXPECTED_SOURCE_SHA256 = (
    "1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5"
)

SOURCE_TEXT = r'''# Cell 4 — OIP v0.2.0 Synthetic Decision Engine

FIELDS = {
    "case_id",
    "evidence_status",
    "review_result",
    "evidence_conflict",
    "prior_state",
}

EVIDENCE_VALUES = {"PRESENT", "MISSING", "UNKNOWN"}
REVIEW_VALUES = {"PASSED", "FAILED", "NOT_REVIEWED"}
STATE_VALUES = {
    "NOT_ASSESSED",
    "PENDING_EVIDENCE",
    "APPROVED",
    "BLOCKED",
}


def decide(case: dict) -> dict:
    """Apply the frozen v0.2.0 demo decision rules."""

    def invalid_result(reason):
        cid = case.get("case_id") if isinstance(case, dict) else None
        prior = case.get("prior_state") if isinstance(case, dict) else None

        if not isinstance(cid, str) or not cid.strip():
            cid = None

        if not isinstance(prior, str) or prior not in STATE_VALUES:
            prior = None

        return {
            "case_id": cid,
            "state": "INVALID_INPUT",
            "reason": reason,
            "prior_state": prior,
        }

    # 1. Input must be a dictionary.
    if not isinstance(case, dict):
        return invalid_result("Input must be a dictionary.")

    # 2. Required and unexpected fields.
    missing = FIELDS - set(case.keys())
    extra = set(case.keys()) - FIELDS

    if missing:
        return invalid_result(
            f"Missing required fields: {sorted(missing)}"
        )

    if extra:
        return invalid_result(
            f"Unexpected fields: {sorted(map(str, extra))}"
        )

    # 3. Validate each field before making a decision.
    cid = case["case_id"]
    evidence = case["evidence_status"]
    review = case["review_result"]
    conflict = case["evidence_conflict"]
    prior = case["prior_state"]

    if not isinstance(cid, str) or not cid.strip():
        return invalid_result("case_id must be a non-empty string.")

    if not isinstance(evidence, str) or evidence not in EVIDENCE_VALUES:
        return invalid_result("Invalid evidence_status.")

    if not isinstance(review, str) or review not in REVIEW_VALUES:
        return invalid_result("Invalid review_result.")

    if type(conflict) is not bool:
        return invalid_result("evidence_conflict must be True or False.")

    if not isinstance(prior, str) or prior not in STATE_VALUES:
        return invalid_result("Invalid prior_state.")

    # 4. Frozen decision precedence.
    if conflict:
        state = "BLOCKED"
        reason = "Contradictory evidence declared."

    elif prior == "BLOCKED":
        state = "BLOCKED"
        reason = "Previous BLOCKED state retained by demo policy."

    elif review == "FAILED":
        state = "BLOCKED"
        reason = "Failed review: v0.2.0 demo policy."

    elif evidence in {"MISSING", "UNKNOWN"}:
        state = "PENDING_EVIDENCE"
        reason = "Evidence is missing or unresolved."

    elif review == "NOT_REVIEWED":
        state = "PENDING_EVIDENCE"
        reason = "Review has not been completed."

    elif evidence == "PRESENT" and review == "PASSED":
        state = "APPROVED"
        reason = "All demo approval conditions are satisfied."

    else:
        state = "PENDING_EVIDENCE"
        reason = "No approval rule was satisfied."

    # 5. Return an explicit, auditable decision record.
    return {
        "case_id": cid,
        "state": state,
        "reason": reason,
        "prior_state": prior,
    }


print("Decision engine defined.")
print("Full rule tests are scheduled for Cell 6.")
'''

source_bytes = SOURCE_TEXT.encode("utf-8")
actual_source_sha256 = hashlib.sha256(source_bytes).hexdigest()

print("Expected SHA-256:", EXPECTED_SOURCE_SHA256)
print("Actual SHA-256:  ", actual_source_sha256)

if actual_source_sha256 != EXPECTED_SOURCE_SHA256:
    raise RuntimeError(
        "SOURCE IDENTITY CHECK FAILED. Stop: do not execute tests."
    )

print("SOURCE IDENTITY CHECK: PASS")

exec(
    compile(SOURCE_TEXT, "verified_oip_v0_2_0_source.py", "exec"),
    globals()
)

print("BASELINE SOURCE LOADED: PASS")

Expected SHA-256: 1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5
Actual SHA-256:   1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5
SOURCE IDENTITY CHECK: PASS
Decision engine defined.
Full rule tests are scheduled for Cell 6.
BASELINE SOURCE LOADED: PASS

In [2]:
# OIP v0.2.0 Baseline Verification
# Cell 3: Prepare Core Decision Test Records

import json

if "decide" not in globals():
    raise RuntimeError(
        "BASELINE ENGINE NOT FOUND. Run and verify Cell 2 first."
    )

if "_CORE_TESTS" in globals():
    raise RuntimeError(
        "CORE TEST RECORDS ALREADY EXIST. Avoid accidental overwrite."
    )

CORE_TESTS = [
    {
        "test_id": "T01",
        "scenario": "Complete file with successful review",
        "input": {
            "case_id": "T01",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "APPROVED",
    },
    {
        "test_id": "T02",
        "scenario": "Conflicting financial documents",
        "input": {
            "case_id": "T02",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": True,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "BLOCKED",
    },
    {
        "test_id": "T03",
        "scenario": "Required medical report missing",
        "input": {
            "case_id": "T03",
            "evidence_status": "MISSING",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "PENDING_EVIDENCE",
    },
    {
        "test_id": "T04",
        "scenario": "Evidence status remains unknown",
        "input": {
            "case_id": "T04",
            "evidence_status": "UNKNOWN",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "PENDING_EVIDENCE",
    },
    {
        "test_id": "T05",
        "scenario": "Infrastructure safety review failed",
        "input": {
            "case_id": "T05",
            "evidence_status": "PRESENT",
            "review_result": "FAILED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "BLOCKED",
    },
    {
        "test_id": "T06",
        "scenario": "Review not yet completed",
        "input": {
            "case_id": "T06",
            "evidence_status": "PRESENT",
            "review_result": "NOT_REVIEWED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "PENDING_EVIDENCE",
    },
    {
        "test_id": "T07",
        "scenario": "Evidence missing and review incomplete",
        "input": {
            "case_id": "T07",
            "evidence_status": "MISSING",
            "review_result": "NOT_REVIEWED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "PENDING_EVIDENCE",
    },
    {
        "test_id": "T08",
        "scenario": "Evidence missing and review failed",
        "input": {
            "case_id": "T08",
            "evidence_status": "MISSING",
            "review_result": "FAILED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "BLOCKED",
    },
    {
        "test_id": "T09",
        "scenario": "Unknown evidence and failed review",
        "input": {
            "case_id": "T09",
            "evidence_status": "UNKNOWN",
            "review_result": "FAILED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "BLOCKED",
    },
    {
        "test_id": "T10",
        "scenario": "Invalid evidence status",
        "input": {
            "case_id": "T10",
            "evidence_status": "INVALID_STATUS",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "T11",
        "scenario": "Required review field missing",
        "input": {
            "case_id": "T11",
            "evidence_status": "PRESENT",
            "evidence_conflict": False,
            "prior_state": "APPROVED",
        },
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "T12",
        "scenario": "Evidence conflict and failed review",
        "input": {
            "case_id": "T12",
            "evidence_status": "PRESENT",
            "review_result": "FAILED",
            "evidence_conflict": True,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "BLOCKED",
    },
    {
        "test_id": "T13",
        "scenario": "Repeat the same valid input",
        "input": {
            "case_id": "T13",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "APPROVED",
    },
    {
        "test_id": "T14",
        "scenario": "Previously blocked case",
        "input": {
            "case_id": "T14",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "BLOCKED",
        },
        "expected": "BLOCKED",
    },
]

# Structural checks only. No decisions have been executed yet.
test_ids = [case["test_id"] for case in CORE_TESTS]

assert len(CORE_TESTS) == 14
assert len(set(test_ids)) == 14
assert all(
    {"test_id", "scenario", "input", "expected"} <= set(case)
    for case in CORE_TESTS
)

print("CORE TEST PREPARATION: PASS")
print("Planned test records:", len(CORE_TESTS))
print("Unique test IDs:", len(set(test_ids)))
print("Decision tests executed: 0")
print("Expected outcomes still require source-rule verification.")

CORE TEST PREPARATION: PASS
Planned test records: 14
Unique test IDs: 14
Decision tests executed: 0
Expected outcomes still require source-rule verification.

In [3]:
# CELL 2 — Verify and load the exact canonical OIP v0.2.0 source

import base64
import gzip
import hashlib

EXPECTED_SOURCE_SHA256 = (
    "1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5"
)

# Compressed, embedded bytes extracted from the original notebook's
# complete decision-engine source cell.
SOURCE_GZIP_B64 = """
H4sIAAAAAAAC/6VX227bRhB951cM6BcJkIk0TfsgIAVUiyqEOJRgyc5DEAhrcmQToXZZLulENQz0I/qF/ZLOXri8SL6lehF3OTPn
zGVnhydwhlkG7+Dfv/+BxXwJd2+Ct8EbWO15eYtlGsMU41SmgkPIb1KOnjebh+fTFbyHew/o58dM4iZN/JFZ4l2aII9xI0tWVrLe
Lmgfv20KlFVWHsjGgm+zNHYv8iIVhbaAtPXgeeHVfBpGZ+HmanJ+GWp0f3kRrsJo7Y/A/zhfrebRH+rxMvoQLT5F/oN3QUrhp47G
ZLUKp0pqNpmfm6dosd4YSVo/eKv1ZN1GMXyUkNI16mZvGUZTwtzU1Or9yXJ5sbhq5H4/X5x90Evyw0twCwmFNMGBCtwYEnJ7CKe/
6YexUfH9SZ5ne6AUwLYQfyGv85LgTmh9nZKiylAGJO5pPWU75XcsSxMb6EGBTAo+NHbVj5DJLQUd3GA5cNkbQkrKMuUUdMqIJjey
5DCTCJGg5NdWdH46dtoZe5ktZ4yEuSg7CmkyAlkWQyAU9Y42Alqn+aDlSuPOc/Y0ucaiYa9lOLQT3rVdO9m1XmBZFdwWRv1zYRwr
RqPuOxOUMfjziGDm0808Wl6u/Z6UyRSJmYfe23Z4x4ZZI/Fg2J3ATwHMeV6VsKtkCdcITEedSoUV+8B7JNhNdsZ9L3vV5D9h3R/W
LN4GcIF/VmmBCTCeQMXxe45xScttilkiDZNdKonEDQXYdpRTkFRJuqS+4l4OhkMth9/LgpFU/yXJG0WvdsxafM6LTmS3/kfLo6g5
G5JjuJeiINIDa3b44DvNocPU7F6JeNkPSAuL5QMq05GxOzyCeQI/B3ClrFMtALL41hihhGxFgbBjX5U3zHUJE+3m3H92xfrFxNc2
Yfe638GNmGngTqjbz41I3cUPLbn+bgTb7eNzp7a/eN7/aQmPlK11uFW4XPBT3OXlXtmkeLnyPUSunWjgXcRsC+ldTi84RXoNvUA/
wcFEu2Fgk2HxOxfdi9E7GWxjl/uc4m0zRr1capxrIbJnbR8k3IV8XVSomM8YXQBPePr6Vv2Mm63qavWodwHMzMXqLtO8wBg1e9cp
ay8aMG2HKtfd6i0aqm2rV2eC09lVrVEU+6ZYCChj1F8Ce1tjRgj2JLQMvg5rqbIoKglWxipRTBgNa9QU9mZkyAX5se9A1wf6vZuG
Xgc9Y2mGdRmNOwPKETQXBsrj/dF57Qj6wYh1hEboDEt3pVBIK06FILK7XrxbTncGvx8EvzDmbpk9I0gFFYtdnmHZA266rDJtJ1d9
PbYo2fn0CBk3VB4hMaEBXoed5XkhqOpV3SapupglUMWBZGUq6ZJoMaLJ88c8jlowavyEb+T7AcAJ/KKGAH0wGafLLKeCSMsRsIqI
sesMW0MsxqJIAu/ocPXYYOWGKv3f2n90jHp8hFJjOS05NQ33sYP6Y0dN1OoYqcZhJWZVZh0vUZY2vvEtJpU6DHQDmw+qX5XKf1rv
bEVdDQAA
"""

compressed_bytes = base64.b64decode("".join(SOURCE_GZIP_B64.split()))
SOURCE_BYTES = gzip.decompress(compressed_bytes)
actual_source_sha256 = hashlib.sha256(SOURCE_BYTES).hexdigest()

print("Expected SHA-256:", EXPECTED_SOURCE_SHA256)
print("Actual SHA-256:  ", actual_source_sha256)

if actual_source_sha256 != EXPECTED_SOURCE_SHA256:
    raise RuntimeError(
        "SOURCE IDENTITY CHECK: FAIL. "
        "The canonical source was not loaded; stop the audit."
    )

print("SOURCE IDENTITY CHECK: PASS")

# Execute only after the complete source bytes pass the hash check.
SOURCE_TEXT = SOURCE_BYTES.decode("utf-8")
exec(
    compile(SOURCE_TEXT, "<canonical-oip-v0.2.0-source-cell>", "exec"),
    globals()
)

if not callable(globals().get("decide")):
    raise RuntimeError("BASELINE SOURCE LOAD: FAIL — decide() is unavailable.")

print("BASELINE SOURCE LOADED: PASS")
print("Source bytes verified:", len(SOURCE_BYTES))
print("Decision tests executed: 0")

Expected SHA-256: 1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5
Actual SHA-256:   1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5
SOURCE IDENTITY CHECK: PASS
Decision engine defined.
Full rule tests are scheduled for Cell 6.
BASELINE SOURCE LOADED: PASS
Source bytes verified: 3421
Decision tests executed: 0

In [4]:
# CELL 4 — Validate Core Test Definitions (Corrected)
# Structural validation only. No decision tests are executed.

required_names = ["decide", "CORE_TESTS"]

missing_names = [
    name for name in required_names
    if name not in globals()
]

if missing_names:
    raise RuntimeError(
        f"CORE TEST SETUP: FAIL — missing objects: {missing_names}"
    )

assert callable(decide), "decide must be callable."
assert isinstance(CORE_TESTS, list), "CORE_TESTS must be a list."
assert len(CORE_TESTS) == 14, (
    f"Expected 14 core tests; found {len(CORE_TESTS)}."
)

test_ids = [test.get("test_id") for test in CORE_TESTS]

assert all(
    isinstance(test_id, str) and test_id.strip()
    for test_id in test_ids
), "Every test must have a non-empty test_id."

assert len(set(test_ids)) == len(test_ids), (
    "Duplicate test IDs detected."
)

required_test_fields = {
    "test_id",
    "scenario",
    "input",
    "expected",
}

for test in CORE_TESTS:
    missing_fields = required_test_fields - set(test.keys())

    assert not missing_fields, (
        f"{test.get('test_id')}: missing fields {sorted(missing_fields)}"
    )

    assert isinstance(test["input"], dict), (
        f"{test['test_id']}: input must be a dictionary."
    )

    assert isinstance(test["expected"], str), (
        f"{test['test_id']}: expected must be a string."
    )

print("CORE TEST DEFINITION CHECK: PASS")
print("Core test records:", len(CORE_TESTS))
print("Unique test IDs:", len(set(test_ids)))
print("Required fields: PASS")
print("Decision tests executed: 0")
print("Records modified: 0")

CORE TEST DEFINITION CHECK: PASS
Core test records: 14
Unique test IDs: 14
Required fields: PASS
Decision tests executed: 0
Records modified: 0

In [5]:
# CELL 5 — Audit Expected Outcomes Against Frozen Source Rules
# This cell does not execute decide().

EXPECTED_RULES = {
    "T01": "APPROVED",
    "T02": "BLOCKED",
    "T03": "PENDING_EVIDENCE",
    "T04": "PENDING_EVIDENCE",
    "T05": "BLOCKED",
    "T06": "PENDING_EVIDENCE",
    "T07": "PENDING_EVIDENCE",
    "T08": "BLOCKED",
    "T09": "BLOCKED",
    "T10": "INVALID_INPUT",
    "T11": "INVALID_INPUT",
    "T12": "BLOCKED",
    "T13": "APPROVED",
    "T14": "BLOCKED",
}

audit_rows = []

for test in CORE_TESTS:
    test_id = test["test_id"]
    declared_expected = test["expected"]
    rule_expected = EXPECTED_RULES.get(test_id)

    if rule_expected is None:
        status = "FAIL_UNEXPECTED_TEST_ID"
    elif declared_expected != rule_expected:
        status = "FAIL_EXPECTED_OUTCOME_MISMATCH"
    else:
        status = "PASS"

    audit_rows.append({
        "test_id": test_id,
        "scenario": test["scenario"],
        "declared_expected": declared_expected,
        "rule_expected": rule_expected,
        "status": status,
    })

import pandas as pd

audit_df = pd.DataFrame(audit_rows)
display(audit_df)

print("\nExpected outcome audit summary:")
print(audit_df["status"].value_counts().to_dict())
print("Decision tests executed: 0")
print("Decision engine called: NO")

,test_id,scenario,declared_expected,rule_expected,status
0,T01,Complete file with successful review,APPROVED,APPROVED,PASS
1,T02,Conflicting financial documents,BLOCKED,BLOCKED,PASS
2,T03,Required medical report missing,PENDING_EVIDENCE,PENDING_EVIDENCE,PASS
3,T04,Evidence status remains unknown,PENDING_EVIDENCE,PENDING_EVIDENCE,PASS
4,T05,Infrastructure safety review failed,BLOCKED,BLOCKED,PASS
5,T06,Review not yet completed,PENDING_EVIDENCE,PENDING_EVIDENCE,PASS
6,T07,Evidence missing and review incomplete,PENDING_EVIDENCE,PENDING_EVIDENCE,PASS
7,T08,Evidence missing and review failed,BLOCKED,BLOCKED,PASS
8,T09,Unknown evidence and failed review,BLOCKED,BLOCKED,PASS
9,T10,Invalid evidence status,INVALID_INPUT,INVALID_INPUT,PASS
10,T11,Required review field missing,INVALID_INPUT,INVALID_INPUT,PASS
11,T12,Evidence conflict and failed review,BLOCKED,BLOCKED,PASS
12,T13,Repeat the same valid input,APPROVED,APPROVED,PASS
13,T14,Previously blocked case,BLOCKED,BLOCKED,PASS

Expected outcome audit summary:
{'PASS': 14}
Decision tests executed: 0
Decision engine called: NO

In [6]:
# CELL 6 — OIP v0.2.0 Core Decision Execution
# Executes the existing 14 test records without recreating them.

import pandas as pd
import json

core_results = []

print("OIP v0.2.0 — CORE DECISION TESTS")
print("Executing existing CORE_TESTS records\n")

for test in CORE_TESTS:
    test_id = test["test_id"]
    expected = test["expected"]
    test_input = test["input"]

    try:
        actual_result = decide(test_input.copy())

        if not isinstance(actual_result, dict):
            raise TypeError(
                "Decision engine did not return a dictionary."
            )

        actual_state = actual_result.get("state")
        status = "PASS" if actual_state == expected else "FAIL"

        core_results.append({
            "test_id": test_id,
            "scenario": test["scenario"],
            "input_json": json.dumps(
                test_input, sort_keys=True
            ),
            "expected_state": expected,
            "actual_state": actual_state,
            "actual_reason": actual_result.get("reason"),
            "actual_prior_state": actual_result.get("prior_state"),
            "status": status,
            "error": None,
        })

    except Exception as exc:
        core_results.append({
            "test_id": test_id,
            "scenario": test["scenario"],
            "input_json": json.dumps(
                test_input, sort_keys=True
            ),
            "expected_state": expected,
            "actual_state": None,
            "actual_reason": None,
            "actual_prior_state": None,
            "status": "ERROR",
            "error": f"{type(exc).__name__}: {exc}",
        })

core_results_df = pd.DataFrame(core_results)

display(
    core_results_df[
        [
            "test_id",
            "expected_state",
            "actual_state",
            "actual_reason",
            "status",
            "error",
        ]
    ]
)

print("\nCORE TEST SUMMARY")
print(core_results_df["status"].value_counts().to_dict())
print("Tests attempted:", len(core_results_df))
print(
    "All 14 tests passed:",
    len(core_results_df) == 14
    and (core_results_df["status"] == "PASS").all()
)
print("Note: PASS evaluates state equality only.")
print("Source-rule and reason verification remains separate.")

OIP v0.2.0 — CORE DECISION TESTS
Executing existing CORE_TESTS records

,test_id,expected_state,actual_state,actual_reason,status,error
0,T01,APPROVED,APPROVED,All demo approval conditions are satisfied.,PASS,None
1,T02,BLOCKED,BLOCKED,Contradictory evidence declared.,PASS,None
2,T03,PENDING_EVIDENCE,PENDING_EVIDENCE,Evidence is missing or unresolved.,PASS,None
3,T04,PENDING_EVIDENCE,PENDING_EVIDENCE,Evidence is missing or unresolved.,PASS,None
4,T05,BLOCKED,BLOCKED,Failed review: v0.2.0 demo policy.,PASS,None
5,T06,PENDING_EVIDENCE,PENDING_EVIDENCE,Review has not been completed.,PASS,None
6,T07,PENDING_EVIDENCE,PENDING_EVIDENCE,Evidence is missing or unresolved.,PASS,None
7,T08,BLOCKED,BLOCKED,Failed review: v0.2.0 demo policy.,PASS,None
8,T09,BLOCKED,BLOCKED,Failed review: v0.2.0 demo policy.,PASS,None
9,T10,INVALID_INPUT,INVALID_INPUT,Invalid evidence_status.,PASS,None
10,T11,INVALID_INPUT,INVALID_INPUT,Missing required fields: ['review_result'],PASS,None
11,T12,BLOCKED,BLOCKED,Contradictory evidence declared.,PASS,None
12,T13,APPROVED,APPROVED,All demo approval conditions are satisfied.,PASS,None
13,T14,BLOCKED,BLOCKED,Previous BLOCKED state retained by demo policy.,PASS,None

CORE TEST SUMMARY
{'PASS': 14}
Tests attempted: 14
All 14 tests passed: True
Note: PASS evaluates state equality only.
Source-rule and reason verification remains separate.

In [7]:
# CELL 7 — Verify Decision Reasons Against Source Rules
# Re-executes the 14 core inputs and checks state + reason.

import pandas as pd

EXPECTED_REASONS = {
    "T01": "All demo approval conditions are satisfied.",
    "T02": "Contradictory evidence declared.",
    "T03": "Evidence is missing or unresolved.",
    "T04": "Evidence is missing or unresolved.",
    "T05": "Failed review: v0.2.0 demo policy.",
    "T06": "Review has not been completed.",
    "T07": "Evidence is missing or unresolved.",
    "T08": "Failed review: v0.2.0 demo policy.",
    "T09": "Failed review: v0.2.0 demo policy.",
    "T10": "Invalid evidence_status.",
    "T11": "Missing required fields: ['review_result']",
    "T12": "Contradictory evidence declared.",
    "T13": "All demo approval conditions are satisfied.",
    "T14": "Previous BLOCKED state retained by demo policy.",
}

reason_results = []

for test in CORE_TESTS:
    test_id = test["test_id"]

    try:
        result = decide(test["input"].copy())

        actual_state = result.get("state")
        actual_reason = result.get("reason")

        expected_state = test["expected"]
        expected_reason = EXPECTED_REASONS[test_id]

        state_ok = actual_state == expected_state
        reason_ok = actual_reason == expected_reason

        if state_ok and reason_ok:
            status = "PASS"
        elif not state_ok and not reason_ok:
            status = "FAIL_STATE_AND_REASON"
        elif not state_ok:
            status = "FAIL_STATE"
        else:
            status = "FAIL_REASON"

        reason_results.append({
            "test_id": test_id,
            "expected_state": expected_state,
            "actual_state": actual_state,
            "expected_reason": expected_reason,
            "actual_reason": actual_reason,
            "state_match": state_ok,
            "reason_match": reason_ok,
            "status": status,
        })

    except Exception as exc:
        reason_results.append({
            "test_id": test_id,
            "expected_state": test["expected"],
            "actual_state": None,
            "expected_reason": EXPECTED_REASONS.get(test_id),
            "actual_reason": None,
            "state_match": False,
            "reason_match": False,
            "status": "ERROR",
        })

reason_results_df = pd.DataFrame(reason_results)

display(reason_results_df)

print("\nREASON VERIFICATION SUMMARY")
print(reason_results_df["status"].value_counts().to_dict())
print("Tests checked:", len(reason_results_df))
print(
    "All states and reasons match:",
    len(reason_results_df) == 14
    and (reason_results_df["status"] == "PASS").all()
)
print(
    "Note: This checks the listed cases only; "
    "it is not exhaustive verification."
)

,test_id,expected_state,actual_state,expected_reason,actual_reason,state_match,reason_match,status
0,T01,APPROVED,APPROVED,All demo approval conditions are satisfied.,All demo approval conditions are satisfied.,True,True,PASS
1,T02,BLOCKED,BLOCKED,Contradictory evidence declared.,Contradictory evidence declared.,True,True,PASS
2,T03,PENDING_EVIDENCE,PENDING_EVIDENCE,Evidence is missing or unresolved.,Evidence is missing or unresolved.,True,True,PASS
3,T04,PENDING_EVIDENCE,PENDING_EVIDENCE,Evidence is missing or unresolved.,Evidence is missing or unresolved.,True,True,PASS
4,T05,BLOCKED,BLOCKED,Failed review: v0.2.0 demo policy.,Failed review: v0.2.0 demo policy.,True,True,PASS
5,T06,PENDING_EVIDENCE,PENDING_EVIDENCE,Review has not been completed.,Review has not been completed.,True,True,PASS
6,T07,PENDING_EVIDENCE,PENDING_EVIDENCE,Evidence is missing or unresolved.,Evidence is missing or unresolved.,True,True,PASS
7,T08,BLOCKED,BLOCKED,Failed review: v0.2.0 demo policy.,Failed review: v0.2.0 demo policy.,True,True,PASS
8,T09,BLOCKED,BLOCKED,Failed review: v0.2.0 demo policy.,Failed review: v0.2.0 demo policy.,True,True,PASS
9,T10,INVALID_INPUT,INVALID_INPUT,Invalid evidence_status.,Invalid evidence_status.,True,True,PASS
10,T11,INVALID_INPUT,INVALID_INPUT,Missing required fields: ['review_result'],Missing required fields: ['review_result'],True,True,PASS
11,T12,BLOCKED,BLOCKED,Contradictory evidence declared.,Contradictory evidence declared.,True,True,PASS
12,T13,APPROVED,APPROVED,All demo approval conditions are satisfied.,All demo approval conditions are satisfied.,True,True,PASS
13,T14,BLOCKED,BLOCKED,Previous BLOCKED state retained by demo policy.,Previous BLOCKED state retained by demo policy.,True,True,PASS

REASON VERIFICATION SUMMARY
{'PASS': 14}
Tests checked: 14
All states and reasons match: True
Note: This checks the listed cases only; it is not exhaustive verification.

In [8]:
# CELL 8 — Prepare 8 Edge Case Tests
# Preparation only. No decision tests are executed.

EDGE_TESTS = [
    {
        "test_id": "E01",
        "scenario": "Whitespace-only case ID",
        "input": {
            "case_id": "   ",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "E02",
        "scenario": "Empty case ID",
        "input": {
            "case_id": "",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "E03",
        "scenario": "Integer used as case ID",
        "input": {
            "case_id": 123,
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "E04",
        "scenario": "Conflict with previous BLOCKED state",
        "input": {
            "case_id": "E04",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": True,
            "prior_state": "BLOCKED",
        },
        "expected": "BLOCKED",
    },
    {
        "test_id": "E05",
        "scenario": "Failed review with previous BLOCKED state",
        "input": {
            "case_id": "E05",
            "evidence_status": "PRESENT",
            "review_result": "FAILED",
            "evidence_conflict": False,
            "prior_state": "BLOCKED",
        },
        "expected": "BLOCKED",
    },
    {
        "test_id": "E06",
        "scenario": "Unknown evidence and unreviewed case",
        "input": {
            "case_id": "E06",
            "evidence_status": "UNKNOWN",
            "review_result": "NOT_REVIEWED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "PENDING_EVIDENCE",
    },
    {
        "test_id": "E07",
        "scenario": "Boolean used as evidence conflict",
        "input": {
            "case_id": "E07",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": 1,
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "E08",
        "scenario": "Invalid prior state",
        "input": {
            "case_id": "E08",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "UNKNOWN_STATE",
        },
        "expected": "INVALID_INPUT",
    },
]

assert len(EDGE_TESTS) == 8
assert len({test["test_id"] for test in EDGE_TESTS}) == 8

for test in EDGE_TESTS:
    assert set(test.keys()) == {
        "test_id", "scenario", "input", "expected"
    }

print("EDGE TEST PREPARATION: PASS")
print("Planned edge tests:", len(EDGE_TESTS))
print("Unique test IDs:", len({t['test_id'] for t in EDGE_TESTS}))
print("Decision tests executed: 0")
print("Records modified: 0")

EDGE TEST PREPARATION: PASS
Planned edge tests: 8
Unique test IDs: 8
Decision tests executed: 0
Records modified: 0

In [9]:
# CELL 9 — Execute 8 Edge Case Tests
# Records actual outputs; does not stop at the first failure.

import pandas as pd

edge_results = []

for test in EDGE_TESTS:
    try:
        result = decide(test["input"].copy())

        if not isinstance(result, dict):
            raise TypeError(
                f"Expected dict; received {type(result).__name__}"
            )

        actual_state = result.get("state")
        expected_state = test["expected"]

        edge_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": expected_state,
            "actual_state": actual_state,
            "actual_reason": result.get("reason"),
            "actual_prior_state": result.get("prior_state"),
            "status": (
                "PASS" if actual_state == expected_state else "FAIL"
            ),
            "error": None,
        })

    except Exception as exc:
        edge_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected"],
            "actual_state": None,
            "actual_reason": None,
            "actual_prior_state": None,
            "status": "ERROR",
            "error": f"{type(exc).__name__}: {exc}",
        })

edge_results_df = pd.DataFrame(edge_results)

display(
    edge_results_df[
        [
            "test_id",
            "scenario",
            "expected_state",
            "actual_state",
            "actual_reason",
            "status",
            "error",
        ]
    ]
)

print("\nEDGE TEST SUMMARY")
print(edge_results_df["status"].value_counts().to_dict())
print("Tests attempted:", len(edge_results_df))
print(
    "All 8 edge tests passed:",
    len(edge_results_df) == 8
    and (edge_results_df["status"] == "PASS").all()
)

,test_id,scenario,expected_state,actual_state,actual_reason,status,error
0,E01,Whitespace-only case ID,INVALID_INPUT,INVALID_INPUT,case_id must be a non-empty string.,PASS,None
1,E02,Empty case ID,INVALID_INPUT,INVALID_INPUT,case_id must be a non-empty string.,PASS,None
2,E03,Integer used as case ID,INVALID_INPUT,INVALID_INPUT,case_id must be a non-empty string.,PASS,None
3,E04,Conflict with previous BLOCKED state,BLOCKED,BLOCKED,Contradictory evidence declared.,PASS,None
4,E05,Failed review with previous BLOCKED state,BLOCKED,BLOCKED,Previous BLOCKED state retained by demo policy.,PASS,None
5,E06,Unknown evidence and unreviewed case,PENDING_EVIDENCE,PENDING_EVIDENCE,Evidence is missing or unresolved.,PASS,None
6,E07,Boolean used as evidence conflict,INVALID_INPUT,INVALID_INPUT,evidence_conflict must be True or False.,PASS,None
7,E08,Invalid prior state,INVALID_INPUT,INVALID_INPUT,Invalid prior_state.,PASS,None

EDGE TEST SUMMARY
{'PASS': 8}
Tests attempted: 8
All 8 edge tests passed: True

In [10]:
# CELL 10 — Prepare 5 Input Validation Tests
# Preparation only; no decision tests are executed.

VALIDATION_TESTS = [
    {
        "test_id": "V01",
        "scenario": "Input is None",
        "input": None,
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "V02",
        "scenario": "Input is a list",
        "input": [],
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "V03",
        "scenario": "Input is a string",
        "input": "not-a-dictionary",
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "V04",
        "scenario": "Unexpected extra field",
        "input": {
            "case_id": "V04",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
            "unexpected_field": "extra",
        },
        "expected": "INVALID_INPUT",
    },
    {
        "test_id": "V05",
        "scenario": "Missing required field",
        "input": {
            "case_id": "V05",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "prior_state": "NOT_ASSESSED",
        },
        "expected": "INVALID_INPUT",
    },
]

assert len(VALIDATION_TESTS) == 5
assert len({
    test["test_id"] for test in VALIDATION_TESTS
}) == 5

print("INPUT VALIDATION PREPARATION: PASS")
print("Planned validation tests:", len(VALIDATION_TESTS))
print("Unique test IDs:", len({
    test["test_id"] for test in VALIDATION_TESTS
}))
print("Decision tests executed: 0")
print("Records modified: 0")

INPUT VALIDATION PREPARATION: PASS
Planned validation tests: 5
Unique test IDs: 5
Decision tests executed: 0
Records modified: 0

In [11]:
# CELL 11 — Execute Input Validation Tests
# Records actual states, reasons, and errors.

import pandas as pd

validation_results = []

for test in VALIDATION_TESTS:
    try:
        result = decide(test["input"])

        if not isinstance(result, dict):
            raise TypeError(
                f"Expected dict; got {type(result).__name__}"
            )

        actual_state = result.get("state")
        expected_state = test["expected"]

        validation_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": expected_state,
            "actual_state": actual_state,
            "actual_reason": result.get("reason"),
            "status": (
                "PASS" if actual_state == expected_state else "FAIL"
            ),
            "error": None,
        })

    except Exception as exc:
        validation_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected"],
            "actual_state": None,
            "actual_reason": None,
            "status": "ERROR",
            "error": f"{type(exc).__name__}: {exc}",
        })

validation_results_df = pd.DataFrame(validation_results)

display(validation_results_df)

print("\nINPUT VALIDATION SUMMARY")
print(validation_results_df["status"].value_counts().to_dict())
print("Tests attempted:", len(validation_results_df))
print(
    "All 5 validation tests passed:",
    len(validation_results_df) == 5
    and (validation_results_df["status"] == "PASS").all()
)

,test_id,scenario,expected_state,actual_state,actual_reason,status,error
0,V01,Input is None,INVALID_INPUT,INVALID_INPUT,Input must be a dictionary.,PASS,None
1,V02,Input is a list,INVALID_INPUT,INVALID_INPUT,Input must be a dictionary.,PASS,None
2,V03,Input is a string,INVALID_INPUT,INVALID_INPUT,Input must be a dictionary.,PASS,None
3,V04,Unexpected extra field,INVALID_INPUT,INVALID_INPUT,Unexpected fields: ['unexpected_field'],PASS,None
4,V05,Missing required field,INVALID_INPUT,INVALID_INPUT,Missing required fields: ['evidence_conflict'],PASS,None

INPUT VALIDATION SUMMARY
{'PASS': 5}
Tests attempted: 5
All 5 validation tests passed: True

In [12]:
# CELL 12 — Prepare 5 Output Contract Tests
# Preparation only. No decision tests are executed.

OUTPUT_CONTRACT_TESTS = [
    {
        "test_id": "O01",
        "scenario": "Valid approval output contract",
        "input": {
            "case_id": "O01",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "APPROVED",
    },
    {
        "test_id": "O02",
        "scenario": "Blocked output contract",
        "input": {
            "case_id": "O02",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": True,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "BLOCKED",
    },
    {
        "test_id": "O03",
        "scenario": "Pending evidence output contract",
        "input": {
            "case_id": "O03",
            "evidence_status": "UNKNOWN",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "PENDING_EVIDENCE",
    },
    {
        "test_id": "O04",
        "scenario": "Invalid input output contract",
        "input": None,
        "expected_state": "INVALID_INPUT",
    },
    {
        "test_id": "O05",
        "scenario": "Missing field output contract",
        "input": {
            "case_id": "O05",
            "evidence_status": "PRESENT",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "INVALID_INPUT",
    },
]

assert len(OUTPUT_CONTRACT_TESTS) == 5
assert len({
    test["test_id"] for test in OUTPUT_CONTRACT_TESTS
}) == 5

print("OUTPUT CONTRACT PREPARATION: PASS")
print("Planned output contract tests:", len(OUTPUT_CONTRACT_TESTS))
print("Unique test IDs:", len({
    test["test_id"] for test in OUTPUT_CONTRACT_TESTS
}))
print("Decision tests executed: 0")
print("Records modified: 0")

OUTPUT CONTRACT PREPARATION: PASS
Planned output contract tests: 5
Unique test IDs: 5
Decision tests executed: 0
Records modified: 0

In [13]:
# CELL 13 — Execute Output Contract Tests
# Checks output keys, basic types, and expected state.

import pandas as pd

REQUIRED_OUTPUT_KEYS = {
    "case_id",
    "state",
    "reason",
    "prior_state",
}

output_contract_results = []

for test in OUTPUT_CONTRACT_TESTS:
    try:
        result = decide(test["input"])

        if not isinstance(result, dict):
            raise TypeError(
                f"Expected dict; got {type(result).__name__}"
            )

        actual_keys = set(result.keys())
        missing_keys = REQUIRED_OUTPUT_KEYS - actual_keys
        extra_keys = actual_keys - REQUIRED_OUTPUT_KEYS

        types_ok = (
            (result.get("case_id") is None
             or isinstance(result.get("case_id"), str))
            and isinstance(result.get("state"), str)
            and isinstance(result.get("reason"), str)
            and (
                result.get("prior_state") is None
                or isinstance(result.get("prior_state"), str)
            )
        )

        state_ok = result.get("state") == test["expected_state"]
        keys_ok = actual_keys == REQUIRED_OUTPUT_KEYS

        status = (
            "PASS" if keys_ok and types_ok and state_ok else "FAIL"
        )

        output_contract_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected_state"],
            "actual_state": result.get("state"),
            "keys_match": keys_ok,
            "missing_keys": sorted(missing_keys),
            "extra_keys": sorted(extra_keys),
            "types_match": types_ok,
            "state_match": state_ok,
            "status": status,
            "error": None,
        })

    except Exception as exc:
        output_contract_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected_state"],
            "actual_state": None,
            "keys_match": False,
            "missing_keys": None,
            "extra_keys": None,
            "types_match": False,
            "state_match": False,
            "status": "ERROR",
            "error": f"{type(exc).__name__}: {exc}",
        })

output_contract_results_df = pd.DataFrame(
    output_contract_results
)

display(output_contract_results_df)

print("\nOUTPUT CONTRACT SUMMARY")
print(output_contract_results_df["status"].value_counts().to_dict())
print("Tests attempted:", len(output_contract_results_df))
print(
    "All 5 output contract tests passed:",
    len(output_contract_results_df) == 5
    and (output_contract_results_df["status"] == "PASS").all()
)

,test_id,scenario,expected_state,actual_state,keys_match,missing_keys,extra_keys,types_match,state_match,status,error
0,O01,Valid approval output contract,APPROVED,APPROVED,True,[],[],True,True,PASS,None
1,O02,Blocked output contract,BLOCKED,BLOCKED,True,[],[],True,True,PASS,None
2,O03,Pending evidence output contract,PENDING_EVIDENCE,PENDING_EVIDENCE,True,[],[],True,True,PASS,None
3,O04,Invalid input output contract,INVALID_INPUT,INVALID_INPUT,True,[],[],True,True,PASS,None
4,O05,Missing field output contract,INVALID_INPUT,INVALID_INPUT,True,[],[],True,True,PASS,None

OUTPUT CONTRACT SUMMARY
{'PASS': 5}
Tests attempted: 5
All 5 output contract tests passed: True

In [14]:
# CELL 14 — Prepare 3 Field Immutability Tests
# Preparation only; no decision tests are executed.

IMMUTABILITY_TESTS = [
    {
        "test_id": "I01",
        "scenario": "Input remains unchanged after approval decision",
        "input": {
            "case_id": "I01",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "APPROVED",
    },
    {
        "test_id": "I02",
        "scenario": "Input remains unchanged after blocked decision",
        "input": {
            "case_id": "I02",
            "evidence_status": "PRESENT",
            "review_result": "PASSED",
            "evidence_conflict": True,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "BLOCKED",
    },
    {
        "test_id": "I03",
        "scenario": "Input remains unchanged after invalid input decision",
        "input": {
            "case_id": "I03",
            "evidence_status": "INVALID",
            "review_result": "PASSED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "INVALID_INPUT",
    },
]

assert len(IMMUTABILITY_TESTS) == 3
assert len({
    test["test_id"] for test in IMMUTABILITY_TESTS
}) == 3

print("IMMUTABILITY TEST PREPARATION: PASS")
print("Planned tests:", len(IMMUTABILITY_TESTS))
print("Unique test IDs:", len({
    test["test_id"] for test in IMMUTABILITY_TESTS
}))
print("Decision tests executed: 0")
print("Input mutation checks executed: 0")

IMMUTABILITY TEST PREPARATION: PASS
Planned tests: 3
Unique test IDs: 3
Decision tests executed: 0
Input mutation checks executed: 0

In [15]:
# CELL 15 — Execute Field Immutability Tests
# Checks input preservation before and after decision execution.

import copy
import pandas as pd

immutability_results = []

for test in IMMUTABILITY_TESTS:
    original_input = test["input"]
    before = copy.deepcopy(original_input)

    try:
        result = decide(original_input)

        unchanged = original_input == before
        state_match = (
            isinstance(result, dict)
            and result.get("state") == test["expected_state"]
        )

        if unchanged and state_match:
            status = "PASS"
        elif not unchanged and not state_match:
            status = "FAIL_MUTATION_AND_STATE"
        elif not unchanged:
            status = "FAIL_INPUT_MUTATION"
        else:
            status = "FAIL_STATE"

        immutability_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected_state"],
            "actual_state": (
                result.get("state")
                if isinstance(result, dict)
                else None
            ),
            "input_unchanged": unchanged,
            "state_match": state_match,
            "status": status,
            "error": None,
        })

    except Exception as exc:
        immutability_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected_state"],
            "actual_state": None,
            "input_unchanged": original_input == before,
            "state_match": False,
            "status": "ERROR",
            "error": f"{type(exc).__name__}: {exc}",
        })

immutability_results_df = pd.DataFrame(immutability_results)

display(immutability_results_df)

print("\nIMMUTABILITY TEST SUMMARY")
print(immutability_results_df["status"].value_counts().to_dict())
print("Tests attempted:", len(immutability_results_df))
print(
    "All 3 tests passed:",
    len(immutability_results_df) == 3
    and (immutability_results_df["status"] == "PASS").all()
)

,test_id,scenario,expected_state,actual_state,input_unchanged,state_match,status,error
0,I01,Input remains unchanged after approval decision,APPROVED,APPROVED,True,True,PASS,None
1,I02,Input remains unchanged after blocked decision,BLOCKED,BLOCKED,True,True,PASS,None
2,I03,Input remains unchanged after invalid input de...,INVALID_INPUT,INVALID_INPUT,True,True,PASS,None

IMMUTABILITY TEST SUMMARY
{'PASS': 3}
Tests attempted: 3
All 3 tests passed: True

In [16]:
# CELL 16 — Configuration Stability Test

import copy
import pandas as pd

config_names = [
    "FIELDS",
    "EVIDENCE_VALUES",
    "REVIEW_VALUES",
    "STATE_VALUES"
]

# Capture configuration before execution
config_before = {
    name: copy.deepcopy(globals()[name])
    for name in config_names
}

# Execute one valid decision
dummy_input = {
    "case_id": "CONF_TEST",
    "evidence_status": "PRESENT",
    "review_result": "PASSED",
    "evidence_conflict": False,
    "prior_state": "NOT_ASSESSED"
}

decision_result = decide(dummy_input)

# Compare configuration after execution
config_results = []

for name in config_names:
    unchanged = config_before[name] == globals()[name]

    config_results.append({
        "config_name": name,
        "unchanged": unchanged,
        "status": "PASS" if unchanged else "FAIL"
    })

config_results_df = pd.DataFrame(config_results)

display(config_results_df)

print("\nCONFIGURATION STABILITY SUMMARY")
print(config_results_df["status"].value_counts().to_dict())
print("Variables checked:", len(config_results_df))
print(
    "All 4 checks passed:",
    len(config_results_df) == 4
    and (config_results_df["status"] == "PASS").all()
)
print("Decision engine result:", decision_result["state"])

       config_name  unchanged status
0           FIELDS       True   PASS
1  EVIDENCE_VALUES       True   PASS
2    REVIEW_VALUES       True   PASS
3     STATE_VALUES       True   PASS

CONFIGURATION STABILITY SUMMARY
{'PASS': 4}
Variables checked: 4
All 4 checks passed: True
Decision engine result: APPROVED

In [17]:
# CELL 17 — Exhaustive Matrix Test (72 Combinations)

import itertools
import pandas as pd

statuses = ["PRESENT", "MISSING", "UNKNOWN"]
reviews = ["PASSED", "FAILED", "NOT_REVIEWED"]
conflicts = [False, True]
priors = [
    "NOT_ASSESSED",
    "PENDING_EVIDENCE",
    "APPROVED",
    "BLOCKED"
]

matrix_results = []

for idx, (status, review, conflict, prior) in enumerate(
    itertools.product(statuses, reviews, conflicts, priors),
    start=1
):
    case = {
        "case_id": f"MATRIX_{idx:03d}",
        "evidence_status": status,
        "review_result": review,
        "evidence_conflict": conflict,
        "prior_state": prior
    }

    # Reference expectations based on the frozen v0.2.0 rules
    if conflict:
        expected = "BLOCKED"
    elif prior == "BLOCKED":
        expected = "BLOCKED"
    elif review == "FAILED":
        expected = "BLOCKED"
    elif status in ["MISSING", "UNKNOWN"]:
        expected = "PENDING_EVIDENCE"
    elif review == "NOT_REVIEWED":
        expected = "PENDING_EVIDENCE"
    elif status == "PRESENT" and review == "PASSED":
        expected = "APPROVED"
    else:
        expected = "PENDING_EVIDENCE"

    try:
        result = decide(case.copy())
        actual = (
            result.get("state")
            if isinstance(result, dict)
            else None
        )
        passed = actual == expected
        error = None

    except Exception as exc:
        actual = None
        passed = False
        error = f"{type(exc).__name__}: {exc}"

    matrix_results.append({
        "case_id": case["case_id"],
        "evidence": status,
        "review": review,
        "conflict": conflict,
        "prior_state": prior,
        "expected": expected,
        "actual": actual,
        "status": "PASS" if passed else "FAIL",
        "error": error
    })

df_matrix = pd.DataFrame(matrix_results)

print("FIRST 10 CASES")
display(df_matrix.head(10))

print("LAST 10 CASES")
display(df_matrix.tail(10))

print("\nEXHAUSTIVE MATRIX SUMMARY")
print(df_matrix["status"].value_counts().to_dict())
print("Cases generated:", len(df_matrix))
print("Failures:", int((df_matrix["status"] == "FAIL").sum()))
print(
    "All 72 cases passed:",
    len(df_matrix) == 72
    and (df_matrix["status"] == "PASS").all()
)

if (df_matrix["status"] == "FAIL").any():
    print("\nFAILED CASES — INVESTIGATION REQUIRED")
    display(df_matrix[df_matrix["status"] == "FAIL"])

FIRST 10 CASES

,case_id,evidence,review,conflict,prior_state,expected,actual,status,error
0,MATRIX_001,PRESENT,PASSED,False,NOT_ASSESSED,APPROVED,APPROVED,PASS,None
1,MATRIX_002,PRESENT,PASSED,False,PENDING_EVIDENCE,APPROVED,APPROVED,PASS,None
2,MATRIX_003,PRESENT,PASSED,False,APPROVED,APPROVED,APPROVED,PASS,None
3,MATRIX_004,PRESENT,PASSED,False,BLOCKED,BLOCKED,BLOCKED,PASS,None
4,MATRIX_005,PRESENT,PASSED,True,NOT_ASSESSED,BLOCKED,BLOCKED,PASS,None
5,MATRIX_006,PRESENT,PASSED,True,PENDING_EVIDENCE,BLOCKED,BLOCKED,PASS,None
6,MATRIX_007,PRESENT,PASSED,True,APPROVED,BLOCKED,BLOCKED,PASS,None
7,MATRIX_008,PRESENT,PASSED,True,BLOCKED,BLOCKED,BLOCKED,PASS,None
8,MATRIX_009,PRESENT,FAILED,False,NOT_ASSESSED,BLOCKED,BLOCKED,PASS,None
9,MATRIX_010,PRESENT,FAILED,False,PENDING_EVIDENCE,BLOCKED,BLOCKED,PASS,None

LAST 10 CASES

,case_id,evidence,review,conflict,prior_state,expected,actual,status,error
62,MATRIX_063,UNKNOWN,FAILED,True,APPROVED,BLOCKED,BLOCKED,PASS,None
63,MATRIX_064,UNKNOWN,FAILED,True,BLOCKED,BLOCKED,BLOCKED,PASS,None
64,MATRIX_065,UNKNOWN,NOT_REVIEWED,False,NOT_ASSESSED,PENDING_EVIDENCE,PENDING_EVIDENCE,PASS,None
65,MATRIX_066,UNKNOWN,NOT_REVIEWED,False,PENDING_EVIDENCE,PENDING_EVIDENCE,PENDING_EVIDENCE,PASS,None
66,MATRIX_067,UNKNOWN,NOT_REVIEWED,False,APPROVED,PENDING_EVIDENCE,PENDING_EVIDENCE,PASS,None
67,MATRIX_068,UNKNOWN,NOT_REVIEWED,False,BLOCKED,BLOCKED,BLOCKED,PASS,None
68,MATRIX_069,UNKNOWN,NOT_REVIEWED,True,NOT_ASSESSED,BLOCKED,BLOCKED,PASS,None
69,MATRIX_070,UNKNOWN,NOT_REVIEWED,True,PENDING_EVIDENCE,BLOCKED,BLOCKED,PASS,None
70,MATRIX_071,UNKNOWN,NOT_REVIEWED,True,APPROVED,BLOCKED,BLOCKED,PASS,None
71,MATRIX_072,UNKNOWN,NOT_REVIEWED,True,BLOCKED,BLOCKED,BLOCKED,PASS,None

EXHAUSTIVE MATRIX SUMMARY
{'PASS': 72}
Cases generated: 72
Failures: 0
All 72 cases passed: True

In [18]:
# CELL 18A — Export Readiness Check
# Read-only diagnostic; does not execute decision tests.

required_variables = [
    "CORE_TESTS",
    "core_results_df",
    "edge_results_df",
    "validation_results_df",
    "output_contract_results_df",
    "immutability_results_df",
    "config_results_df",
    "df_matrix"
]

print("=== OIP EXPORT READINESS CHECK ===")

for name in required_variables:
    exists = name in globals()
    print(f"{name}: {'FOUND' if exists else 'NOT FOUND'}")

print("\n=== AVAILABLE RESULT DATAFRAMES ===")

for name, value in list(globals().items()):
    if name.startswith("_"):
        continue

    if hasattr(value, "columns") and hasattr(value, "shape"):
        print(f"{name}: shape={value.shape}, columns={list(value.columns)}")

print("\nDiagnostic only: no decision tests executed.")

=== OIP EXPORT READINESS CHECK ===
CORE_TESTS: FOUND
core_results_df: FOUND
edge_results_df: FOUND
validation_results_df: FOUND
output_contract_results_df: FOUND
immutability_results_df: FOUND
config_results_df: FOUND
df_matrix: FOUND

=== AVAILABLE RESULT DATAFRAMES ===
audit_df: shape=(14, 5), columns=['test_id', 'scenario', 'declared_expected', 'rule_expected', 'status']
core_results_df: shape=(14, 9), columns=['test_id', 'scenario', 'input_json', 'expected_state', 'actual_state', 'actual_reason', 'actual_prior_state', 'status', 'error']
reason_results_df: shape=(14, 8), columns=['test_id', 'expected_state', 'actual_state', 'expected_reason', 'actual_reason', 'state_match', 'reason_match', 'status']
edge_results_df: shape=(8, 8), columns=['test_id', 'scenario', 'expected_state', 'actual_state', 'actual_reason', 'actual_prior_state', 'status', 'error']
validation_results_df: shape=(5, 7), columns=['test_id', 'scenario', 'expected_state', 'actual_state', 'actual_reason', 'status', 'error']
output_contract_results_df: shape=(5, 11), columns=['test_id', 'scenario', 'expected_state', 'actual_state', 'keys_match', 'missing_keys', 'extra_keys', 'types_match', 'state_match', 'status', 'error']
immutability_results_df: shape=(3, 8), columns=['test_id', 'scenario', 'expected_state', 'actual_state', 'input_unchanged', 'state_match', 'status', 'error']
config_results_df: shape=(4, 3), columns=['config_name', 'unchanged', 'status']
df_matrix: shape=(72, 9), columns=['case_id', 'evidence', 'review', 'conflict', 'prior_state', 'expected', 'actual', 'status', 'error']

Diagnostic only: no decision tests executed.

In [19]:
# CELL 18B — Final Audit Export
# Exports existing test outputs only; does not rerun decision tests.

import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone
import pandas as pd

out_dir = Path("/kaggle/working")
out_dir.mkdir(parents=True, exist_ok=True)

# Required existing result tables and their section names
result_tables = {
    "Core": core_results_df,
    "Core_Reason": reason_results_df,
    "Edge": edge_results_df,
    "Validation": validation_results_df,
    "Output_Contract": output_contract_results_df,
    "Immutability": immutability_results_df,
    "Configuration": config_results_df,
    "Exhaustive_Matrix": df_matrix,
}

# Fail closed if a required table is missing or malformed
for section, df in result_tables.items():
    if not isinstance(df, pd.DataFrame):
        raise TypeError(f"{section}: expected a pandas DataFrame")

    if df.empty:
        raise ValueError(f"{section}: result table is empty")

# Convert every existing result row into a JSON-safe record.
# Preserve all columns rather than guessing a common schema.
records = []

for section, df in result_tables.items():
    for row in df.to_dict(orient="records"):
        safe_row = {}

        for key, value in row.items():
            if hasattr(value, "item"):
                try:
                    value = value.item()
                except (ValueError, TypeError):
                    pass

            if pd.isna(value) if not isinstance(value, (dict, list, tuple)) else False:
                value = None

            safe_row[str(key)] = value

        records.append({
            "section": section,
            "result": safe_row
        })

# Include row counts and observed status counts for transparency
section_summary = {}

for section, df in result_tables.items():
    summary = {"records": len(df)}

    if "status" in df.columns:
        summary["status_counts"] = {
            str(k): int(v)
            for k, v in df["status"].value_counts(dropna=False).items()
        }

    section_summary[section] = summary

report = {
    "protocol": "OIP v0.2.0 Baseline Verification",
    "artifact_type": "test_result_export",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "execution_note": (
        "Exports existing notebook result tables. "
        "This cell does not rerun decision tests."
    ),
    "section_summary": section_summary,
    "total_exported_rows": len(records),
    "records": records
}

json_path = out_dir / "OIP_v0.2.0_AUDIT_REPORT.json"
csv_path = out_dir / "OIP_v0.2.0_AUDIT_RESULTS.csv"

json_bytes = json.dumps(
    report,
    indent=2,
    ensure_ascii=False,
    default=str
).encode("utf-8")

json_path.write_bytes(json_bytes)

# CSV: one row per exported result, with section plus serialized row data
csv_records = [
    {
        "section": item["section"],
        "result_json": json.dumps(
            item["result"],
            ensure_ascii=False,
            sort_keys=True,
            default=str
        )
    }
    for item in records
]

pd.DataFrame(csv_records).to_csv(
    csv_path,
    index=False,
    encoding="utf-8"
)

def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

print("=== OIP v0.2.0 EXPORT SUMMARY ===")
print("Section counts:")

for section, summary in section_summary.items():
    print(f"{section}: {summary}")

print("\nTotal exported rows:", len(records))
print("Expected from current tables:", sum(len(df) for df in result_tables.values()))
print("JSON exists:", json_path.exists())
print("CSV exists:", csv_path.exists())
print("JSON bytes:", json_path.stat().st_size)
print("CSV bytes:", csv_path.stat().st_size)

print("\nSHA-256")
print("JSON:", sha256_file(json_path))
print("CSV: ", sha256_file(csv_path))

# Basic read-back validation
loaded_report = json.loads(json_path.read_text(encoding="utf-8"))
loaded_csv = pd.read_csv(csv_path)

print("\nREAD-BACK VALIDATION")
print("JSON record count matches:", len(loaded_report["records"]) == len(records))
print("CSV row count matches:", len(loaded_csv) == len(records))
print("Export test execution count: 0")

=== OIP v0.2.0 EXPORT SUMMARY ===
Section counts:
Core: {'records': 14, 'status_counts': {'PASS': 14}}
Core_Reason: {'records': 14, 'status_counts': {'PASS': 14}}
Edge: {'records': 8, 'status_counts': {'PASS': 8}}
Validation: {'records': 5, 'status_counts': {'PASS': 5}}
Output_Contract: {'records': 5, 'status_counts': {'PASS': 5}}
Immutability: {'records': 3, 'status_counts': {'PASS': 3}}
Configuration: {'records': 4, 'status_counts': {'PASS': 4}}
Exhaustive_Matrix: {'records': 72, 'status_counts': {'PASS': 72}}

Total exported rows: 125
Expected from current tables: 125
JSON exists: True
CSV exists: True
JSON bytes: 47932
CSV bytes: 35412

SHA-256
JSON: 39541a6abfc0996b97b7290df9abf6f3ed5de63c66c5dc7f57115529b4883098
CSV:  f6636373f8d6724cc17f4a5a7ec93d9a8d816edf599a04155093e1016c67493e

READ-BACK VALIDATION
JSON record count matches: True
CSV row count matches: True
Export test execution count: 0

In [20]:
# CELL 19 — Export Integrity Verification
# Read-only verification of the exported JSON and CSV artifacts.

import json
import hashlib
from pathlib import Path
import pandas as pd

out_dir = Path("/kaggle/working")
json_path = out_dir / "OIP_v0.2.0_AUDIT_REPORT.json"
csv_path = out_dir / "OIP_v0.2.0_AUDIT_RESULTS.csv"

assert json_path.exists(), "JSON artifact missing"
assert csv_path.exists(), "CSV artifact missing"

# Re-read artifacts
report = json.loads(json_path.read_text(encoding="utf-8"))
csv_df = pd.read_csv(csv_path)

# Verify counts
json_records = report["records"]
csv_count = len(csv_df)

count_match = (
    len(json_records) == report["total_exported_rows"]
    and len(json_records) == csv_count
)

# Verify section counts against exported records
section_counts = {}
section_status_counts = {}

for section in report["section_summary"]:
    section_records = [
        item for item in json_records
        if item["section"] == section
    ]
    section_counts[section] = len(section_records)

    statuses = {}
    for item in section_records:
        status = item["result"].get("status")
        if status is not None:
            statuses[str(status)] = statuses.get(str(status), 0) + 1

    section_status_counts[section] = statuses

section_counts_match = all(
    section_counts[section] == report["section_summary"][section]["records"]
    for section in section_counts
)

all_statuses_pass = all(
    all(status == "PASS" for status in counts)
    for counts in section_status_counts.values()
    if counts
)

# Recompute hashes
def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

json_hash_1 = sha256_file(json_path)
json_hash_2 = sha256_file(json_path)
csv_hash_1 = sha256_file(csv_path)
csv_hash_2 = sha256_file(csv_path)

hash_reproducible = (
    json_hash_1 == json_hash_2
    and csv_hash_1 == csv_hash_2
)

print("=== EXPORT INTEGRITY VERIFICATION ===")
print("JSON records:", len(json_records))
print("CSV rows:", csv_count)
print("Record counts match:", count_match)
print("Section counts match:", section_counts_match)
print("All recorded statuses PASS:", all_statuses_pass)
print("Hash recomputation consistent:", hash_reproducible)

print("\nSection counts:")
print(section_counts)

print("\nJSON SHA-256:", json_hash_1)
print("CSV SHA-256: ", csv_hash_1)

print("\nOVERALL CHECK:")
print(
    "PASS" if (
        count_match
        and section_counts_match
        and all_statuses_pass
        and hash_reproducible
    ) else "FAIL"
)

=== EXPORT INTEGRITY VERIFICATION ===
JSON records: 125
CSV rows: 125
Record counts match: True
Section counts match: True
All recorded statuses PASS: True
Hash recomputation consistent: True

Section counts:
{'Core': 14, 'Core_Reason': 14, 'Edge': 8, 'Validation': 5, 'Output_Contract': 5, 'Immutability': 3, 'Configuration': 4, 'Exhaustive_Matrix': 72}

JSON SHA-256: 39541a6abfc0996b97b7290df9abf6f3ed5de63c66c5dc7f57115529b4883098
CSV SHA-256:  f6636373f8d6724cc17f4a5a7ec93d9a8d816edf599a04155093e1016c67493e

OVERALL CHECK:
PASS

In [21]:
# CELL 20 — Final Audit Gate
# Read-only checks. Does not rerun decision tests.

import json
import hashlib
from pathlib import Path
import pandas as pd

out_dir = Path("/kaggle/working")
json_path = out_dir / "OIP_v0.2.0_AUDIT_REPORT.json"
csv_path = out_dir / "OIP_v0.2.0_AUDIT_RESULTS.csv"

checks = {}

# 1. Required result tables
tables = {
    "Core": core_results_df,
    "Core_Reason": reason_results_df,
    "Edge": edge_results_df,
    "Validation": validation_results_df,
    "Output_Contract": output_contract_results_df,
    "Immutability": immutability_results_df,
    "Configuration": config_results_df,
    "Exhaustive_Matrix": df_matrix,
}

checks["all_result_tables_present"] = all(
    isinstance(df, pd.DataFrame) and not df.empty
    for df in tables.values()
)

# 2. Planned unique test-record count
planned_counts = {
    "Core": 14,
    "Edge": 8,
    "Validation": 5,
    "Output_Contract": 5,
    "Immutability": 3,
    "Configuration": 4,
    "Exhaustive_Matrix": 72,
}

observed_counts = {
    name: len(tables[name])
    for name in planned_counts
}

checks["planned_record_counts_match"] = (
    observed_counts == planned_counts
)

checks["planned_unique_records_total_111"] = (
    sum(observed_counts.values()) == 111
)

# 3. All existing status columns must be PASS
status_checks = {}

for name, df in tables.items():
    if "status" in df.columns:
        status_checks[name] = bool(
            df["status"].eq("PASS").all()
        )
    else:
        status_checks[name] = False

checks["all_table_statuses_pass"] = all(status_checks.values())

# 4. Export artifacts and content counts
checks["json_exists"] = json_path.exists()
checks["csv_exists"] = csv_path.exists()

if checks["json_exists"] and checks["csv_exists"]:
    report = json.loads(json_path.read_text(encoding="utf-8"))
    csv_df = pd.read_csv(csv_path)

    checks["json_record_count_matches"] = (
        len(report["records"]) == report["total_exported_rows"]
    )
    checks["csv_count_matches_json"] = (
        len(csv_df) == len(report["records"])
    )

    expected_export_rows = sum(len(df) for df in tables.values())
    checks["exported_rows_match_current_tables"] = (
        len(report["records"]) == expected_export_rows
    )

    json_hash = hashlib.sha256(json_path.read_bytes()).hexdigest()
    csv_hash = hashlib.sha256(csv_path.read_bytes()).hexdigest()
else:
    checks["json_record_count_matches"] = False
    checks["csv_count_matches_json"] = False
    checks["exported_rows_match_current_tables"] = False
    json_hash = None
    csv_hash = None

# 5. Source identity: report whether the original hash variable is available.
expected_source_hash = (
    "1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5"
)

source_hash_candidates = [
    name for name in globals()
    if "source" in name.lower() and "hash" in name.lower()
]

print("=== OIP v0.2.0 FINAL AUDIT GATE ===")

for name, result in checks.items():
    print(f"{name}: {'PASS' if result else 'FAIL'}")

print("\nObserved planned-record counts:")
print(observed_counts)
print("Unique planned records:", sum(observed_counts.values()))
print("Exported rows:", len(report["records"]) if checks["json_exists"] else "N/A")

print("\nSource hash variables found:", source_hash_candidates)
print("Expected canonical source hash:", expected_source_hash)
print("Note: source identity is not independently re-hashed by this cell.")

print("\nJSON SHA-256:", json_hash)
print("CSV SHA-256: ", csv_hash)

all_checks_pass = all(checks.values())

print("\nFINAL AUDIT GATE:", "PASS" if all_checks_pass else "FAIL")
print("Release status: RESEARCH-STAGE ONLY")
print("Production/scientific approval: NOT GRANTED")

=== OIP v0.2.0 FINAL AUDIT GATE ===
all_result_tables_present: PASS
planned_record_counts_match: PASS
planned_unique_records_total_111: PASS
all_table_statuses_pass: PASS
json_exists: PASS
csv_exists: PASS
json_record_count_matches: PASS
csv_count_matches_json: PASS
exported_rows_match_current_tables: PASS

Observed planned-record counts:
{'Core': 14, 'Edge': 8, 'Validation': 5, 'Output_Contract': 5, 'Immutability': 3, 'Configuration': 4, 'Exhaustive_Matrix': 72}
Unique planned records: 111
Exported rows: 125

Source hash variables found: ['expected_source_hash']
Expected canonical source hash: 1bc5ce14aa25d8788b28f1ee08a78ee2db343d0ea02b0e67bb08da5e7a0e4dc5
Note: source identity is not independently re-hashed by this cell.

JSON SHA-256: 39541a6abfc0996b97b7290df9abf6f3ed5de63c66c5dc7f57115529b4883098
CSV SHA-256:  f6636373f8d6724cc17f4a5a7ec93d9a8d816edf599a04155093e1016c67493e

FINAL AUDIT GATE: PASS
Release status: RESEARCH-STAGE ONLY
Production/scientific approval: NOT GRANTED

In [22]:
# CELL 21 — Precedence Tests (3)
# Tests the frozen rule priority without changing prior results.

import pandas as pd

PRECEDENCE_TESTS = [
    {
        "test_id": "P01",
        "scenario": "Conflict outranks prior BLOCKED and FAILED review",
        "input": {
            "case_id": "P01",
            "evidence_status": "PRESENT",
            "review_result": "FAILED",
            "evidence_conflict": True,
            "prior_state": "BLOCKED",
        },
        "expected_state": "BLOCKED",
        "expected_reason": "Contradictory evidence declared.",
    },
    {
        "test_id": "P02",
        "scenario": "Prior BLOCKED outranks FAILED review",
        "input": {
            "case_id": "P02",
            "evidence_status": "PRESENT",
            "review_result": "FAILED",
            "evidence_conflict": False,
            "prior_state": "BLOCKED",
        },
        "expected_state": "BLOCKED",
        "expected_reason": "Previous BLOCKED state retained by demo policy.",
    },
    {
        "test_id": "P03",
        "scenario": "FAILED review outranks missing evidence",
        "input": {
            "case_id": "P03",
            "evidence_status": "MISSING",
            "review_result": "FAILED",
            "evidence_conflict": False,
            "prior_state": "NOT_ASSESSED",
        },
        "expected_state": "BLOCKED",
        "expected_reason": "Failed review: v0.2.0 demo policy.",
    },
]

precedence_results = []

for test in PRECEDENCE_TESTS:
    try:
        result = decide(test["input"].copy())

        state_match = result.get("state") == test["expected_state"]
        reason_match = result.get("reason") == test["expected_reason"]

        precedence_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected_state"],
            "actual_state": result.get("state"),
            "expected_reason": test["expected_reason"],
            "actual_reason": result.get("reason"),
            "state_match": state_match,
            "reason_match": reason_match,
            "status": "PASS" if state_match and reason_match else "FAIL",
            "error": None,
        })

    except Exception as exc:
        precedence_results.append({
            "test_id": test["test_id"],
            "scenario": test["scenario"],
            "expected_state": test["expected_state"],
            "actual_state": None,
            "expected_reason": test["expected_reason"],
            "actual_reason": None,
            "state_match": False,
            "reason_match": False,
            "status": "ERROR",
            "error": f"{type(exc).__name__}: {exc}",
        })

precedence_results_df = pd.DataFrame(precedence_results)

display(precedence_results_df)

print("\nPRECEDENCE TEST SUMMARY")
print(precedence_results_df["status"].value_counts().to_dict())
print("Tests attempted:", len(precedence_results_df))
print(
    "All 3 precedence tests passed:",
    len(precedence_results_df) == 3
    and precedence_results_df["status"].eq("PASS").all()
)

,test_id,scenario,expected_state,actual_state,expected_reason,actual_reason,state_match,reason_match,status,error
0,P01,Conflict outranks prior BLOCKED and FAILED review,BLOCKED,BLOCKED,Contradictory evidence declared.,Contradictory evidence declared.,True,True,PASS,None
1,P02,Prior BLOCKED outranks FAILED review,BLOCKED,BLOCKED,Previous BLOCKED state retained by demo policy.,Previous BLOCKED state retained by demo policy.,True,True,PASS,None
2,P03,FAILED review outranks missing evidence,BLOCKED,BLOCKED,Failed review: v0.2.0 demo policy.,Failed review: v0.2.0 demo policy.,True,True,PASS,None

PRECEDENCE TEST SUMMARY
{'PASS': 3}
Tests attempted: 3
All 3 precedence tests passed: True

In [23]:
# CELL 22 — Final Export Update
# Rebuilds exports from existing results; does not rerun decision tests.

import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone
import pandas as pd

out_dir = Path("/kaggle/working")

result_tables = {
    "Core": core_results_df,
    "Core_Reason": reason_results_df,
    "Edge": edge_results_df,
    "Validation": validation_results_df,
    "Output_Contract": output_contract_results_df,
    "Immutability": immutability_results_df,
    "Configuration": config_results_df,
    "Precedence": precedence_results_df,
    "Exhaustive_Matrix": df_matrix,
}

# Fail closed if a result table is missing, empty, or has failures.
for section, df in result_tables.items():
    if not isinstance(df, pd.DataFrame) or df.empty:
        raise ValueError(f"{section}: result table missing or empty")

    if "status" not in df.columns or not df["status"].eq("PASS").all():
        raise ValueError(f"{section}: missing status column or non-PASS result")

# The 114 planned unique test records exclude supplemental reason checks.
planned_unique_count = sum(
    len(result_tables[name])
    for name in [
        "Core", "Edge", "Validation", "Output_Contract",
        "Immutability", "Configuration", "Precedence",
        "Exhaustive_Matrix"
    ]
)

if planned_unique_count != 114:
    raise ValueError(
        f"Expected 114 planned unique records; found {planned_unique_count}"
    )

records = []

for section, df in result_tables.items():
    for row in df.to_dict(orient="records"):
        safe_row = {}

        for key, value in row.items():
            if hasattr(value, "item"):
                try:
                    value = value.item()
                except (ValueError, TypeError):
                    pass

            if value is None:
                safe_row[str(key)] = None
            elif isinstance(value, float) and pd.isna(value):
                safe_row[str(key)] = None
            else:
                safe_row[str(key)] = value

        records.append({
            "section": section,
            "result": safe_row
        })

# Supplemental core-reason checks are exported separately.
for row in reason_results_df.to_dict(orient="records"):
    safe_row = {}
    for key, value in row.items():
        if hasattr(value, "item"):
            try:
                value = value.item()
            except (ValueError, TypeError):
                pass
        if value is None or (
            isinstance(value, float) and pd.isna(value)
        ):
            value = None
        safe_row[str(key)] = value

    records.append({
        "section": "Core_Reason",
        "result": safe_row
    })

section_summary = {}

for section, df in result_tables.items():
    section_summary[section] = {
        "records": len(df),
        "status_counts": {
            str(k): int(v)
            for k, v in df["status"].value_counts(dropna=False).items()
        }
    }

section_summary["Core_Reason"] = {
    "records": len(reason_results_df),
    "status_counts": {
        str(k): int(v)
        for k, v in reason_results_df["status"].value_counts(dropna=False).items()
    }
}

report = {
    "protocol": "OIP v0.2.0 Baseline Verification",
    "artifact_type": "test_result_export",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "planned_unique_test_records": planned_unique_count,
    "supplemental_core_reason_records": len(reason_results_df),
    "total_exported_rows": len(records),
    "execution_note": (
        "Exports existing notebook result tables. "
        "No decision tests were rerun in this export cell."
    ),
    "release_status": "RESEARCH-STAGE ONLY",
    "production_or_scientific_approval": "NOT GRANTED",
    "section_summary": section_summary,
    "records": records,
}

json_path = out_dir / "OIP_v0.2.0_AUDIT_REPORT.json"
csv_path = out_dir / "OIP_v0.2.0_AUDIT_RESULTS.csv"

json_path.write_text(
    json.dumps(report, indent=2, ensure_ascii=False, default=str),
    encoding="utf-8"
)

csv_records = [
    {
        "section": item["section"],
        "result_json": json.dumps(
            item["result"],
            ensure_ascii=False,
            sort_keys=True,
            default=str
        )
    }
    for item in records
]

pd.DataFrame(csv_records).to_csv(
    csv_path, index=False, encoding="utf-8"
)

def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

# Read-back verification
loaded_json = json.loads(json_path.read_text(encoding="utf-8"))
loaded_csv = pd.read_csv(csv_path)

checks = {
    "planned_unique_records_114": planned_unique_count == 114,
    "json_count_matches": len(loaded_json["records"]) == len(records),
    "csv_count_matches": len(loaded_csv) == len(records),
    "precedence_records_present": (
        section_summary["Precedence"]["records"] == 3
    ),
    "all_recorded_statuses_pass": all(
        all(count_status == "PASS" for count_status in summary["status_counts"])
        for summary in section_summary.values()
    ),
}

print("=== FINAL EXPORT UPDATE ===")
print("Planned unique test records:", planned_unique_count)
print("Supplemental core-reason records:", len(reason_results_df))
print("Total exported rows:", len(records))
print("\nSection counts:")
for section, summary in section_summary.items():
    print(f"{section}: {summary}")

print("\nRead-back checks:")
for name, passed in checks.items():
    print(f"{name}: {'PASS' if passed else 'FAIL'}")

print("\nJSON SHA-256:", sha256_file(json_path))
print("CSV SHA-256: ", sha256_file(csv_path))
print("JSON bytes:", json_path.stat().st_size)
print("CSV bytes:", csv_path.stat().st_size)

print(
    "\nEXPORT UPDATE:",
    "PASS" if all(checks.values()) else "FAIL"
)
print("Decision tests rerun by this cell: 0")
print("Release status: RESEARCH-STAGE ONLY")

=== FINAL EXPORT UPDATE ===
Planned unique test records: 114
Supplemental core-reason records: 14
Total exported rows: 142

Section counts:
Core: {'records': 14, 'status_counts': {'PASS': 14}}
Core_Reason: {'records': 14, 'status_counts': {'PASS': 14}}
Edge: {'records': 8, 'status_counts': {'PASS': 8}}
Validation: {'records': 5, 'status_counts': {'PASS': 5}}
Output_Contract: {'records': 5, 'status_counts': {'PASS': 5}}
Immutability: {'records': 3, 'status_counts': {'PASS': 3}}
Configuration: {'records': 4, 'status_counts': {'PASS': 4}}
Precedence: {'records': 3, 'status_counts': {'PASS': 3}}
Exhaustive_Matrix: {'records': 72, 'status_counts': {'PASS': 72}}

Read-back checks:
planned_unique_records_114: PASS
json_count_matches: PASS
csv_count_matches: PASS
precedence_records_present: PASS
all_recorded_statuses_pass: PASS

JSON SHA-256: dcaf592e8eda430f55d58ecbb06db815f54f24421d4d0afcc8cde5e99b1d3be3
CSV SHA-256:  53d7019cc53ad2206991cd7179cfada7e70421e0c89ed6bfc7f87a870c5713aa
JSON bytes: 55119
CSV bytes: 40738

EXPORT UPDATE: PASS
Decision tests rerun by this cell: 0
Release status: RESEARCH-STAGE ONLY

In [24]:
# CELL 23 — Corrected Final Export
# Existing results only. No decision tests are rerun.

import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone
import pandas as pd

out_dir = Path("/kaggle/working")

planned_tables = {
    "Core": core_results_df,
    "Edge": edge_results_df,
    "Validation": validation_results_df,
    "Output_Contract": output_contract_results_df,
    "Immutability": immutability_results_df,
    "Configuration": config_results_df,
    "Precedence": precedence_results_df,
    "Exhaustive_Matrix": df_matrix,
}

supplemental_tables = {
    "Core_Reason": reason_results_df,
}

# Validate the existing test results.
for section, df in {**planned_tables, **supplemental_tables}.items():
    if not isinstance(df, pd.DataFrame) or df.empty:
        raise ValueError(f"{section}: missing or empty result table")

    if "status" not in df.columns or not df["status"].eq("PASS").all():
        raise ValueError(f"{section}: failed or missing status results")

planned_count = sum(len(df) for df in planned_tables.values())
supplemental_count = sum(len(df) for df in supplemental_tables.values())

if planned_count != 114:
    raise ValueError(f"Expected 114 planned records; found {planned_count}")

if supplemental_count != 14:
    raise ValueError(
        f"Expected 14 supplemental reason records; found {supplemental_count}"
    )

all_tables = {**planned_tables, **supplemental_tables}
records = []

for section, df in all_tables.items():
    for row in df.to_dict(orient="records"):
        clean_row = {}

        for key, value in row.items():
            if hasattr(value, "item"):
                try:
                    value = value.item()
                except (ValueError, TypeError):
                    pass

            if value is None or (
                isinstance(value, float) and pd.isna(value)
            ):
                value = None

            clean_row[str(key)] = value

        records.append({
            "section": section,
            "result": clean_row
        })

if len(records) != 128:
    raise ValueError(f"Expected 128 export rows; found {len(records)}")

section_summary = {}

for section, df in all_tables.items():
    section_summary[section] = {
        "records": len(df),
        "status_counts": {
            str(k): int(v)
            for k, v in df["status"].value_counts(dropna=False).items()
        }
    }

report = {
    "protocol": "OIP v0.2.0 Baseline Verification",
    "artifact_type": "test_result_export",
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "planned_unique_test_records": planned_count,
    "supplemental_core_reason_records": supplemental_count,
    "total_exported_rows": len(records),
    "note": (
        "Core_Reason results are supplemental and included exactly once. "
        "This cell exports existing results and does not rerun decision tests."
    ),
    "release_status": "RESEARCH-STAGE ONLY",
    "production_or_scientific_approval": "NOT GRANTED",
    "section_summary": section_summary,
    "records": records,
}

json_path = out_dir / "OIP_v0.2.0_AUDIT_REPORT.json"
csv_path = out_dir / "OIP_v0.2.0_AUDIT_RESULTS.csv"

json_path.write_text(
    json.dumps(report, indent=2, ensure_ascii=False, default=str),
    encoding="utf-8"
)

csv_rows = [
    {
        "section": item["section"],
        "result_json": json.dumps(
            item["result"],
            ensure_ascii=False,
            sort_keys=True,
            default=str
        )
    }
    for item in records
]

pd.DataFrame(csv_rows).to_csv(
    csv_path, index=False, encoding="utf-8"
)

# Read-back verification
loaded_json = json.loads(json_path.read_text(encoding="utf-8"))
loaded_csv = pd.read_csv(csv_path)

checks = {
    "planned_records_114": planned_count == 114,
    "supplemental_reason_records_14": supplemental_count == 14,
    "total_export_rows_128": len(records) == 128,
    "json_count_matches": len(loaded_json["records"]) == 128,
    "csv_count_matches": len(loaded_csv) == 128,
    "all_sections_pass": all(
        all(status == "PASS" for status in summary["status_counts"])
        for summary in section_summary.values()
    ),
    "core_reason_included_once": (
        sum(1 for item in records if item["section"] == "Core_Reason") == 14
    ),
}

def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

print("=== CORRECTED FINAL EXPORT ===")
print("Planned unique test records:", planned_count)
print("Supplemental reason records:", supplemental_count)
print("Total exported rows:", len(records))

print("\nSection counts:")
for section, summary in section_summary.items():
    print(f"{section}: {summary}")

print("\nFINAL CHECKS")
for name, passed in checks.items():
    print(f"{name}: {'PASS' if passed else 'FAIL'}")

print("\nJSON SHA-256:", sha256_file(json_path))
print("CSV SHA-256: ", sha256_file(csv_path))
print("JSON bytes:", json_path.stat().st_size)
print("CSV bytes:", csv_path.stat().st_size)

print(
    "\nCORRECTED EXPORT STATUS:",
    "PASS" if all(checks.values()) else "FAIL"
)
print("Decision tests rerun: 0")
print("Release status: RESEARCH-STAGE ONLY")

=== CORRECTED FINAL EXPORT ===
Planned unique test records: 114
Supplemental reason records: 14
Total exported rows: 128

Section counts:
Core: {'records': 14, 'status_counts': {'PASS': 14}}
Edge: {'records': 8, 'status_counts': {'PASS': 8}}
Validation: {'records': 5, 'status_counts': {'PASS': 5}}
Output_Contract: {'records': 5, 'status_counts': {'PASS': 5}}
Immutability: {'records': 3, 'status_counts': {'PASS': 3}}
Configuration: {'records': 4, 'status_counts': {'PASS': 4}}
Precedence: {'records': 3, 'status_counts': {'PASS': 3}}
Exhaustive_Matrix: {'records': 72, 'status_counts': {'PASS': 72}}
Core_Reason: {'records': 14, 'status_counts': {'PASS': 14}}

FINAL CHECKS
planned_records_114: PASS
supplemental_reason_records_14: PASS
total_export_rows_128: PASS
json_count_matches: PASS
csv_count_matches: PASS
all_sections_pass: PASS
core_reason_included_once: PASS

JSON SHA-256: a1f387bcf9a855ea9a9cc233f9697661274d871d45ce85d0347e7f564c6b17bd
CSV SHA-256:  b4637bda0989e66fe3bf20428340f29a7f0a4269ad31a063ca7a1f2b8c576b84
JSON bytes: 49676
CSV bytes: 36536

CORRECTED EXPORT STATUS: PASS
Decision tests rerun: 0
Release status: RESEARCH-STAGE ONLY

In [25]:
!pip install reportlab -q

In [26]:
# CELL 24 — Final PDF Report
# Generates a research-stage report from current export artifacts.

from pathlib import Path
import hashlib
import json
from datetime import datetime, timezone

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak
)

out_dir = Path("/kaggle/working")
json_path = out_dir / "OIP_v0.2.0_AUDIT_REPORT.json"
csv_path = out_dir / "OIP_v0.2.0_AUDIT_RESULTS.csv"
pdf_path = out_dir / "OIP_v0.2.0_Audit_Report.pdf"

if not json_path.exists() or not csv_path.exists():
    raise FileNotFoundError("Corrected JSON/CSV export is missing.")

report = json.loads(json_path.read_text(encoding="utf-8"))

json_hash = hashlib.sha256(json_path.read_bytes()).hexdigest()
csv_hash = hashlib.sha256(csv_path.read_bytes()).hexdigest()

if report.get("planned_unique_test_records") != 114:
    raise ValueError("Unexpected planned test-record count.")

if report.get("supplemental_core_reason_records") != 14:
    raise ValueError("Unexpected supplemental reason-record count.")

if report.get("total_exported_rows") != 128 or len(report.get("records", [])) != 128:
    raise ValueError("Unexpected exported row count.")

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(
    name="ReportTitle",
    parent=styles["Title"],
    alignment=TA_CENTER,
    fontSize=18,
    leading=23,
    spaceAfter=14
))
styles.add(ParagraphStyle(
    name="SmallHash",
    parent=styles["BodyText"],
    fontSize=7,
    leading=9,
    wordWrap="CJK"
))

doc = SimpleDocTemplate(
    str(pdf_path),
    pagesize=letter,
    rightMargin=42,
    leftMargin=42,
    topMargin=42,
    bottomMargin=42
)

story = []

story.append(Paragraph(
    "OIP v0.2.0 Baseline Verification Report",
    styles["ReportTitle"]
))
story.append(Paragraph(
    "<b>Status:</b> RESEARCH-STAGE ONLY<br/>"
    "<b>Scientific/production approval:</b> NOT GRANTED<br/>"
    f"<b>Report generated (UTC):</b> "
    f"{datetime.now(timezone.utc).isoformat()}",
    styles["BodyText"]
))
story.append(Spacer(1, 16))

story.append(Paragraph("1. Executive Summary", styles["Heading1"]))
story.append(Paragraph(
    "This report documents the supplied notebook outputs for a synthetic "
    "baseline verification of the OIP v0.2.0 decision engine. The export "
    "contains 114 planned unique test records and 14 supplemental core-reason "
    "verification records, for 128 exported rows. The reported checks passed. "
    "This result is limited to the tested inputs and recorded checks.",
    styles["BodyText"]
))
story.append(Spacer(1, 12))

story.append(Paragraph("2. Test Results", styles["Heading1"]))

section_data = [["Section", "Records", "Reported status"]]
for section, summary in report["section_summary"].items():
    counts = summary.get("status_counts", {})
    section_data.append([
        section,
        str(summary.get("records", "")),
        ", ".join(f"{k}: {v}" for k, v in counts.items()) or "Not recorded"
    ])

table = Table(section_data, colWidths=[175, 65, 230], repeatRows=1)
table.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E2F3")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
    ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 8),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("LEFTPADDING", (0, 0), (-1, -1), 5),
    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
]))
story.append(table)
story.append(Spacer(1, 12))

story.append(Paragraph("3. Claim Boundaries and Limitations", styles["Heading1"]))
story.append(Paragraph(
    "The recorded PASS results support only the specified software checks "
    "on the tested inputs. They do not establish scientific validity, causal "
    "validity, real-world safety, security certification, production readiness, "
    "or compliance with any later OIP version. The reference expectations for "
    "the exhaustive matrix were separately coded from the stated rules, but "
    "were not independently validated by an external auditor.",
    styles["BodyText"]
))
story.append(Spacer(1, 12))

story.append(Paragraph("4. Export Integrity", styles["Heading1"]))
story.append(Paragraph(
    "The notebook output reported successful JSON/CSV read-back and row-count "
    "checks. SHA-256 hashes below identify the exact exported files used to "
    "generate this report. A hash can detect byte-level changes when compared "
    "against a trusted recorded value; it does not by itself prove the content "
    "is correct or prevent tampering.",
    styles["BodyText"]
))
story.append(Spacer(1, 8))

story.append(Paragraph("JSON SHA-256", styles["Heading2"]))
story.append(Paragraph(json_hash, styles["SmallHash"]))
story.append(Spacer(1, 6))
story.append(Paragraph("CSV SHA-256", styles["Heading2"]))
story.append(Paragraph(csv_hash, styles["SmallHash"]))
story.append(Spacer(1, 12))

story.append(Paragraph("5. Release Decision", styles["Heading1"]))
story.append(Paragraph(
    "<b>Decision: RESEARCH-STAGE ONLY.</b> The recorded baseline tests and "
    "corrected export checks are reported as passing. Independent scientific "
    "validation and production approval have not been granted. The notebook, "
    "source identity evidence, and limitations should accompany these artifacts "
    "when shared.",
    styles["BodyText"]
))

doc.build(story)

# Verify the generated PDF exists and is non-empty.
if not pdf_path.exists() or pdf_path.stat().st_size == 0:
    raise RuntimeError("PDF generation failed.")

print("PDF GENERATED:", pdf_path.name)
print("PDF bytes:", pdf_path.stat().st_size)
print("JSON SHA-256:", json_hash)
print("CSV SHA-256:", csv_hash)
print("PDF existence check: PASS")
print("Claim boundary: RESEARCH-STAGE ONLY")

PDF GENERATED: OIP_v0.2.0_Audit_Report.pdf
PDF bytes: 4167
JSON SHA-256: a1f387bcf9a855ea9a9cc233f9697661274d871d45ce85d0347e7f564c6b17bd
CSV SHA-256: b4637bda0989e66fe3bf20428340f29a7f0a4269ad31a063ca7a1f2b8c576b84
PDF existence check: PASS
Claim boundary: RESEARCH-STAGE ONLY